EventCrushV001/Controllers/CreateController.cs
using System.Web.Mvc;
using MySql.Data.MySqlClient;
using System;

namespace EventCrush.Controllers
{
    public class CreateController : Controller
    {
        public ActionResult PrivateUser()
        {
            return View();
        }

        public ActionResult CorporateUser()
        {
            return View();
        }

        public static MySqlConnection GetConnection(string host, string user, string pwd, string db)
        {
            string conStr = string.Format("server={0};uid={1};pwd={2};database={3}", host, user, pwd, db);
            var con = new MySqlConnection();
            con.ConnectionString = conStr;
            con.Open();
            return con;
        }

        public static MySqlConnection GetDefaultConnection()
        {
            return GetConnection("localhost", "root", "", "EventCrush");
        }

        public ActionResult Submit(string Fornavn, string Efternavn, string Email, int Telefonnummer, string Brugernavn, string Password, string Vejnavn, int Postnummer, string By, string Land, int Vejnummer)
        {
            var con = GetDefaultConnection();
            MySqlCommand cmd = new MySqlCommand();
            cmd.Connection = con;
            cmd.CommandText = "insert into private_user(Username,PW,FirstName,LastName,Email,PhoneNumber) values (@Username, @PW, @FirstName, @LastName, @Email, @PhoneNumber)";
            cmd.Prepare();
            cmd.Parameters.AddWithValue("@Username", Brugernavn);
            cmd.Parameters.AddWithValue("@PW", Password);
            cmd.Parameters.AddWithValue("@FirstName", Fornavn);
            cmd.Parameters.AddWithValue("@LastName", Efternavn);
            cmd.Parameters.AddWithValue("@Email", Email);
            cmd.Parameters.AddWithValue("@PhoneNumber", Telefonnummer);
            cmd.ExecuteNonQuery();
            cmd.CommandText = "insert into address(Road, ZipCode, Town, Country, RoadNumber) values (@Road, @ZipCode, @Town, @Country, @RoadNumber)";
            cmd.Parameters.AddWithValue("@Road", Vejnavn);
            cmd.Parameters.AddWithValue("@ZipCode", Postnummer);
            cmd.Parameters.AddWithValue("@Town", By);
            cmd.Parameters.AddWithValue("@Country", Land);
            cmd.Parameters.AddWithValue("@RoadNumber", Vejnummer);
            cmd.ExecuteNonQuery();
            if (con != null) { con.Close(); }
            return RedirectToAction("Search_Event", "Home");
        }
    }
}

EventCrushV001/Controllers/HomeController.cs
using System.Web.Mvc;
using MySql.Data.MySqlClient;
using System;

namespace EventCrush.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Modify this template to jump-start your ASP.NET MVC application.";

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Search_Event()
        {
            return View();
        }
    }
}

EventCrushV001/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

EventCrushV001/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

EventCrushV001/Views/Home/Index.cshtml
@{
    ViewBag.Title = "EventCrush - Forside";
}
<!-- Content: Start -->
<div class="container-fluid">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 center-content"><img src="Content/img/logo.png" class="animated bounceInDown"><h1 class="animated fadeIn">Velkommen til EventCrush,<br>Hvad har du lyst til?</h1></div>
        <div class="col-md-2"></div>
    </div>
    <div class="row" style="margin-top:100px;">
        <div class="col-md-3 animated fadeIn">
            <div class="card hvr-curl-top-left">
                <div class="card--media">
                    <a href="#">
                        <img src="Content/img/category/koncert.jpg" class="card--media--image" />
                        <div class="card--bottom"></div>
                        <img src="Content/img/category-icon/music.png" class="card--media--icon" />
                        <h3 class="card--headline">Koncert</h3>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-md-3 animated fadeIn center-content">
            <div class="card hvr-curl-top-left">
                <div class="card--media">
                    <a href="#">
                        <img src="Content/img/category/sport.jpg" class="card--media--image" />
                        <div class="card--bottom"></div>
                        <img src="Content/img/category-icon/sport.png" class="card--media--icon" />
                        <h3 class="card--headline">Sport</h3>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-md-3 animated fadeIn center-content">
            <div class="card hvr-curl-top-left">
                <div class="card--media">
                    <a href="#">
                        <img src="Content/img/category/market.jpg" class="card--media--image" />
                        <div class="card--bottom"></div>
                        <img src="Content/img/category-icon/market.png" class="card--media--icon" />
                        <h3 class="card--headline">Marked</h3>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-md-3 animated fadeIn center-content">
            <div class="card hvr-curl-top-left">
                <div class="card--media">
                    <a href="#">
                        <img src="Content/img/category/science.jpg" class="card--media--image" />
                        <div class="card--bottom"></div>
                        <img src="Content/img/category-icon/science.png" class="card--media--icon" />
                        <h3 class="card--headline">Videnskab</h3>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Content: End -->

EventCrushV001/Views/Home/Search_Event.cshtml
@{
    ViewBag.Title = "EventCrush - Find Event";
}

<!-- Content: Start -->
<div class="container-fluid">
    <div class="row">
        <div class="col-md-2 right-content"><img src="~/Content/img/logo.png" class="animated bounceInDown"></div>
        <div class="col-md-8 center-content">
            <a href="@Url.Action("PrivateUser","Create")" class="button button-big" style="margin-right:50px"><img src="@Url.Content("~/Content/img/ui-icon/map-w.png")" style="height:35px;margin-top:1px;" /> Find Events på Kort</a>
            <a href="@Url.Action("PrivateUser","Create")" class="button button-big"><img src="@Url.Content("~/Content/img/ui-icon/category-w.png")" style="height:35px;margin-top:-4px;" /> Se Kategorier</a>
        </div>
        <div class="col-md-4"></div>
    </div>
    <div class="row" style="margin-top:100px;">
        <div class="col-md-3"></div>
        <div class="col-md-6 center-content">
            <form class="form-inline">
                <div class="form-group" style="width:80%;">
                    <label class="sr-only">Søg efter Postnummer</label>
                    <input type="zip" class="form-control-1" placeholder="Søg efter Postnummer" required>
                </div>
                <button type="submit" class="button"><img src="~/Content/img/ui-icon/search-w.png" style="height:35px;"></button>
            </form>
            <div class="col-md-3"></div>
        </div>
    </div>